1990eam/locodeamosentretodos

- db/migrate/20200730232031_create_applications.rb
created Applications model:
role:references
user:references
status
> created Applications model

- db/migrate/20200730231658_create_collaborators.rb
created Collaborators model
role:references 
user:references 
status
> created Collaborators model

- db/migrate/20200730231429_create_roles.rb
Created Roles model
name
project:references
> created Roles model

- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- test/controllers/projects_controller_test.rb
- test/policies/project_policy_test.rb
created Projects Controller and Project Policy
> created Projects Controller and Project Policy

- app/models/application.rb
- app/models/collaborator.rb
- app/models/project.rb
- app/models/role.rb
> added missing models

- db/seeds.rb
> basic seed

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/application_requests/_new.scss
- app/controllers/application_requests_controller.rb
- app/controllers/projects_controller.rb
- app/policies/application_request_policy.rb
- app/views/application_requests/_modal_window.html.erb
- app/views/application_requests/create.html.erb
- app/views/application_requests/new.html.erb
- app/views/applications/create.html.erb
- app/views/applications/new.html.erb
- app/views/pages/home.html.erb
- app/views/projects/index.html.erb
- config/routes.rb
- db/migrate/20200801175820_create_active_storage_tables.active_storage.rb
- db/migrate/20200801180945_add_about_me_to_application_requests.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/application_requests_controller_test.rb
- test/controllers/applications_controller_test.rb
- test/policies/application_policy_test.rb
- test/policies/application_request_policy_test.rb
first iteration of modal window in feed
> Modal window first iteration

- app/models/level.rb
- app/models/project.rb
- app/models/role.rb
- app/models/technology.rb
Chequear las validaciones de Technology, Skill y Level
> Validations level technology skill

- app/assets/stylesheets/pages/application_requests/_new.scss
- app/assets/stylesheets/pages/index.scss
- app/controllers/application_requests_controller.rb
- app/models/application_request.rb
- app/models/role.rb
- app/policies/application_request_policy.rb
- app/views/application_requests/new.html.erb
- app/views/projects/index.html.erb
- db/migrate/20200804230701_add_default_to_application_requests.rb
- db/schema.rb
- db/seeds.rb
falta enchufar seleccion de rol al aplicar. hasta entonces no se va a crear la application
> User can apply to a project

- app/assets/stylesheets/pages/application_requests/_new.scss
- app/assets/stylesheets/pages/projects/projects.scss
- app/controllers/application_requests_controller.rb
- app/views/application_requests/new.html.erb
- db/migrate/20200808143548_change_column_name_in_project.rb
> Form application

- app/assets/stylesheets/pages/roles/roles-show-new.scss
- app/views/shared/_roles_show_new.html.erb
- db/migrate/20200808143548_change_column_name_in_project.rb
- db/schema.rb
Arregle el grid para las cards, pero hay un problema con el footer que no pude solucionar
> Implement grid

- app/assets/stylesheets/pages/projects/_show.scss
- app/assets/stylesheets/pages/roles/roles-show-new.scss
agrego grid al project main view. 
deja de romperse horizontalmente cuando se cambia de tabs.
sigue rompiendose verticalmente
> Project view griddeation ftw

- app/assets/stylesheets/pages/projects/_show.scss
- app/views/projects/show.html.erb
el contenedor de las role cards se expande para mostrar todas los roles.
el sidebar acompaña en el scroll
> More project show improvements

- app/assets/stylesheets/pages/application_requests/my_project_request.scss
- app/controllers/application_requests_controller.rb
- app/policies/application_request_policy.rb
- app/views/application_requests/index.html.erb
- app/views/application_requests/my_project_request.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Esta funcionando la primera ruta para aceptar o declinar una aplicación.
Faltan detalles del front-end
> Accept application

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- db/migrate/20200811224542_delete_links_from_projects.rb
cambie colores de navbar y footer
> change color of the navbar, the footer and btn primary

- app/assets/stylesheets/pages/projects/_index.scss
- app/controllers/projects_controller.rb
- app/javascript/packs/application.js
- app/javascript/pages/projects/index.js
- app/views/projects/index.html.erb
- app/views/shared/_add_skill_modal.html.erb
agrego un modal que se activa con JS solo si el usuario està logueado.
si current_user.skills < 1 salta la modal preguntando si quiere agregar su primer skill
> Modal if user has no skills

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/application_requests/_new.scss
- app/controllers/application_requests_controller.rb
- app/javascript/packs/application.js
- app/javascript/pages/application_requests/new.js
- app/javascript/pages/projects/index.js
- app/models/user.rb
- app/policies/collaborator_policy.rb
- app/policies/project_policy.rb
- app/views/application_requests/_card.html.erb
- app/views/application_requests/index.html.erb
- app/views/application_requests/my_project_request.html.erb
- app/views/application_requests/new.html.erb
- app/views/projects/show.html.erb
- config/application.rb
- config/routes.rb
- db/seeds.rb
- test/policies/collaborator_policy_test.rb
fixes varios
+
un usuario solo puede ver un proyecto si es colaborador o owner
> Pundit policies

- app/javascript/packs/application.js
- app/javascript/pages/projects/index.js
- app/javascript/shared/avatar_tooltips.js
- app/views/application_requests/create.html.erb
- app/views/projects/_index-card.html.erb
- app/views/projects/show.html.erb
si se hace hover de los avatars en el project show aparece un tooltip con el nombre del colaborador y el role que desempeña.
mañana lo implemento en el resto de las cards
> added tooltips JS function to display tooltips if you hover on avatars

- app/policies/application_request_policy.rb
- app/policies/project_policy.rb
- app/views/projects/_index-card.html.erb
- app/views/projects/index.html.erb
- db/schema.rb
cambio la logica del link de las cards del project feed:
si sos colaborador o project owner te manda al project view, sino al project application request
> Collaborators cant apply again

- app/controllers/roles_controller.rb
- app/views/projects/show.html.erb
- app/views/shared/_roles_show_new.html.erb
saco tags harcodeados de techs usados en el rol, los reemplazo por el helper pick_tech_icon
agrego avatar al rol en el caso de que estè ocupado por alguien y mensaje de si està ocupado o no
saco la progressbar que estaba hardcodeada
> Limpio role.cards

- app/assets/stylesheets/pages/application_requests/_my_project_request.scss
- app/assets/stylesheets/pages/application_requests/_new.scss
- app/assets/stylesheets/pages/projects/my_projects.scss
- app/controllers/application_requests_controller.rb
- app/javascript/pages/application_requests/new.js
- app/views/application_requests/my_project_request.html.erb
- app/views/application_requests/new.html.erb
- app/views/projects/my_projects.html.erb
- app/views/projects/show.html.erb
- app/views/shared/_applications_show.html.erb
Arreglo de las cards de applications request con las tecnologias ya en back-end
> arreglo de contenido de cards

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/application_requests/_my_project_request.scss
- app/assets/stylesheets/pages/application_requests/my_project_request.scss
- app/assets/stylesheets/pages/index.scss
- app/views/application_requests/my_project_request.html.erb
- app/views/application_requests/new.html.erb
- app/views/projects/show.html.erb
- app/views/shared/_applications_show.html.erb
Ahora si tendria que estar funcionando el show de project sin romperse
> Arreglos view request

- app/views/projects/show.html.erb
Ya esta arreglado lo que se habia roto misteriosamente
> arreglo de la vista de show project

- app/assets/stylesheets/pages/projects/my_projects.scss
- app/views/application_requests/index.html.erb
- app/views/projects/_index-card.html.erb
Arregle los contributors que estaban hardcodeados y cambie al español en la card principal
> arreglo color de botones en mis proyectos

- app/views/application_requests/index.html.erb
Avisenme si el tamaño les parece bien o prefieren algo mas grande
> finalmente quite todo lo hardcodeado

- app/assets/stylesheets/pages/roles/roles-show-new.scss
- app/assets/stylesheets/pages/suggestions/index.scss
- app/controllers/roles_controller.rb
- app/policies/requirement_policy.rb
- app/views/projects/show.html.erb
- app/views/roles/edit.html.erb
- app/views/shared/_roles_show_new.html.erb
- app/views/suggestions/_index.html.erb
- config/routes.rb
estilo a las cards de suggestions
se puede editar y borrar un role y su requirement
> Last week fixes 2

- app/assets/stylesheets/pages/projects/_show.scss
- app/views/projects/show.html.erb
- app/views/shared/_roles_show_new.html.erb
Esta la imagen ligada al proyecto, si no tiene imagen cargada, queda la que estaba hardcodeada por defecto.
Ordene los componentes de la card de roles, no me termina de convencer la opción de borrar colaborador en esa card...por definir
> logo de proyecto y arreglo en card

- app/assets/stylesheets/pages/projects/my_projects.scss
- app/views/projects/my_projects.html.erb
Mejora de card de mis proyectos, cambio de botones por iconos y ajuste de ancho.
> cambio de botones por iconos

- app/assets/stylesheets/pages/application_requests/_new.scss
- app/views/application_requests/new.html.erb
> aumento de imagen de proyecto en sidecard de new-application

- app/models/project.rb
- app/views/projects/my_projects.html.erb
Se arregló la vista de mis proyectos cuando no creaste ninguno
> Fix my projects view

- app/controllers/application_requests_controller.rb
- app/policies/application_request_policy.rb
- app/views/application_requests/index.html.erb
- app/views/pages/about.html.erb
- app/views/pages/home.html.erb
- app/views/projects/show.html.erb
- config/routes.rb
> Fixes part4
